# global variables
PAGE_SIZE = 4096
PAGE_RANGE_SIZE = 16
MERGE_THRESH = PAGE_SIZE * PAGE_RANGE_SIZE * 4
PAGE_RECORD_SIZE = 512
POOL_SIZE = 1024

# record meta-data columns
INDIRECTION_COLUMN = 0
RID_COLUMN = 1
TIMESTAMP_COLUMN = 2
SCHEMA_ENCODING_COLUMN = 3
